version: '3'

services: 
    reviews:
        image: 'bbalbon/trippy_advisors_calendar_widget:reviews'
        depends_on:
            - 'database'
        ports:
            - '3001:3001'


    database:
        image: mongo:latest